// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/simonjohansson/go-linter/manifest (interfaces: ManifestReader)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/simonjohansson/go-linter/model"
	reflect "reflect"
)

// MockManifestReader is a mock of ManifestReader interface
type MockManifestReader struct {
	ctrl     *gomock.Controller
	recorder *MockManifestReaderMockRecorder
}

// MockManifestReaderMockRecorder is the mock recorder for MockManifestReader
type MockManifestReaderMockRecorder struct {
	mock *MockManifestReader
}

// NewMockManifestReader creates a new mock instance
func NewMockManifestReader(ctrl *gomock.Controller) *MockManifestReader {
	mock := &MockManifestReader{ctrl: ctrl}
	mock.recorder = &MockManifestReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockManifestReader) EXPECT() *MockManifestReaderMockRecorder {
	return m.recorder
}

// ParseManifest mocks base method
func (m *MockManifestReader) ParseManifest(arg0 string) (model.Manifest, error) {
	ret := m.ctrl.Call(m, "ParseManifest", arg0)
	ret0, _ := ret[0].(model.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseManifest indicates an expected call of ParseManifest
func (mr *MockManifestReaderMockRecorder) ParseManifest(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseManifest", reflect.TypeOf((*MockManifestReader)(nil).ParseManifest), arg0)
}
